services:
  apache:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html # Sincroniza a pasta local src com o diretório do Apache
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pipocaqueimada
    ports:
      - "3306:3306" # Mapeia a porta do MySQL

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80" # Mapeia a porta do phpMyAdmin para 8081

#lembrar:
#docker-compose up -d - ReInicia o conteineres; 
#docker-compose down - Para os conteineres.
